version: 0.2

Environment:
  ComputeType: "BUILD_GENERAL1_SMALL"
  Image: "aws/codebuild/nodejs:8.11.0"
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo done building
artifacts:
  files:
    - "**/*"
  base-directory: dist/spa
